/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafeteria.management.system;
import db.CategoryDb;
import db.ProductDb;
import java.util.*;
import model.Category;
import model.Product;
/**
 *
 * @author DELL
 */
public class Add_product extends javax.swing.JFrame {

    /**
     * Creates new form Add_product
     */
    public Add_product() {
        initComponents();
        jbtnsave.setEnabled(false);
    }
    public void validatetextfields(){
        String Name= jtxtname.getText();
        String Price = jtxtprice.getText();
        if(!Name.equals("") && !Price.equals("")){
           jbtnsave.setEnabled(true);
        }else{
            jbtnsave.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnclose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jtxtprice = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jbtnsave = new javax.swing.JButton();
        jbtnclear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 134));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/new product.png"))); // NOI18N
        jLabel1.setText("New Products");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 161, -1));

        jbtnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jbtnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncloseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 94, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Category :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 129, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Price :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 164, -1, -1));

        jtxtname.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtxtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnameKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 93, 239, -1));

        jtxtprice.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jtxtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtpriceKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 163, 239, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 129, 239, -1));

        jbtnsave.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jbtnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save_1.png"))); // NOI18N
        jbtnsave.setText("save");
        jbtnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 205, -1, -1));

        jbtnclear.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jbtnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        jbtnclear.setText("clear");
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 207, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/small-page-background.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Add_product().setVisible(true);
    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jbtncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jbtncloseActionPerformed

    private void jtxtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnameKeyReleased
        // TODO add your handling code here:
        validatetextfields();
    }//GEN-LAST:event_jtxtnameKeyReleased

    private void jtxtpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpriceKeyReleased
        // TODO add your handling code here:
        validatetextfields();
    }//GEN-LAST:event_jtxtpriceKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<Category> list = CategoryDb.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while(itr.hasNext()){
            Category categoryObj = itr.next();
            jComboBox1.addItem(categoryObj.getName());
        }
    }//GEN-LAST:event_formComponentShown

    private void jbtnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsaveActionPerformed
        // TODO add your handling code here:
        Product product = new Product();
        product.setName(jtxtname.getText());
        product.setCategory((String)jComboBox1.getSelectedItem());
        product.setPrice(jtxtprice.getText());
        ProductDb.save(product);
        setVisible(false);
        new Add_product().setVisible(true);
    }//GEN-LAST:event_jbtnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JButton jbtnclose;
    private javax.swing.JButton jbtnsave;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JTextField jtxtprice;
    // End of variables declaration//GEN-END:variables
}
