/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafeteria.management.system;

import db.UserDb;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author DELL
 */
public class SignUp extends javax.swing.JFrame {
    public String EmailPattern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
    public String Phone_NumberPattern = "^[0-9]*$";

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        jbtnsave.setEnabled(false);
    }
    public void clear(){
        jtxtname.setText("");
        jtxtemail.setText("");
        jtxtphone.setText("");
        jtxtpassword.setText("");
        jtxtsq.setText("");
        jtxtanswer.setText("");
        jbtnsave.setEnabled(false);
    }
    public void validateFields(){
        String Name = jtxtname.getText();
        String Email = jtxtemail.getText();
        String Phone_Number = jtxtphone.getText();
        String Password = jtxtpassword.getText();
        String Security_question = jtxtsq.getText();
        String Answer = jtxtanswer.getText();
        if(!Name.equals("") && Email.matches(EmailPattern) && Phone_Number.matches(Phone_NumberPattern) && Phone_Number.length()==10 && !Password.equals("") && !Security_question.equals("") && !Answer.equals("")){
           jbtnsave.setEnabled(true); 
        }else{
             jbtnsave.setEnabled(false);
        }
    }

        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtname = new javax.swing.JTextField();
        jtxtemail = new javax.swing.JTextField();
        jtxtphone = new javax.swing.JTextField();
        jtxtpassword = new javax.swing.JPasswordField();
        jtxtsq = new javax.swing.JTextField();
        jtxtanswer = new javax.swing.JTextField();
        jbtnsave = new javax.swing.JButton();
        jbtnexit = new javax.swing.JButton();
        jbtnlogin = new javax.swing.JButton();
        jbtnforgetpassword = new javax.swing.JButton();
        jbtnclear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        setForeground(new java.awt.Color(255, 204, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 190, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 148, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Email :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 188, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 259, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Phone Number :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 222, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Security Question :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 290, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Answer :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 330, -1, -1));

        jtxtname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtnameKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 145, 229, -1));

        jtxtemail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtemailKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 185, 229, -1));

        jtxtphone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtphoneActionPerformed(evt);
            }
        });
        jtxtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtphoneKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 219, 229, -1));

        jtxtpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpasswordActionPerformed(evt);
            }
        });
        jtxtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtpasswordKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 253, 229, -1));

        jtxtsq.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtsq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsqKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtsq, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 287, 229, -1));

        jtxtanswer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtanswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtanswerKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 327, 229, -1));

        jbtnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save_1.png"))); // NOI18N
        jbtnsave.setText("Save");
        jbtnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        jbtnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit small.png"))); // NOI18N
        jbtnexit.setText("Exit");
        jbtnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnexitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        jbtnlogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        jbtnlogin.setText("Login");
        jbtnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnloginActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        jbtnforgetpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnforgetpassword.setText("Forget Password?");
        jbtnforgetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnforgetpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnforgetpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        jbtnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        jbtnclear.setText("Clear");
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/un.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -50, 1370, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpasswordActionPerformed

    private void jbtnforgetpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnforgetpasswordActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Forgetpassword().setVisible(true);
    }//GEN-LAST:event_jbtnforgetpasswordActionPerformed
private JFrame frame;
    private void jbtnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnexitActionPerformed
      frame = new JFrame("Exit");
      if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to Exit?","Sign Up",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
      {
          System.exit(0);
      }
    }//GEN-LAST:event_jbtnexitActionPerformed

    private void jbtnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsaveActionPerformed
       User user = new User();
       user.setName(jtxtname.getText());
       user.setEmail(jtxtemail.getText());
       user.setPhone_Number(jtxtphone.getText());
       user.setPassword(jtxtpassword.getText());
       user.setSecurity_question(jtxtsq.getText());
       user.setAnswer(jtxtanswer.getText());
       UserDb.save(user);
       clear();
    }//GEN-LAST:event_jbtnsaveActionPerformed

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
      clear();
    }//GEN-LAST:event_jbtnclearActionPerformed

    private void jtxtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtphoneActionPerformed

    private void jtxtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtnameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jtxtnameKeyReleased

    private void jtxtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtemailKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jtxtemailKeyReleased

    private void jtxtphoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtphoneKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jtxtphoneKeyReleased

    private void jtxtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpasswordKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jtxtpasswordKeyReleased

    private void jtxtsqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsqKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jtxtsqKeyReleased

    private void jtxtanswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtanswerKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jtxtanswerKeyReleased

    private void jbtnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnloginActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jbtnloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JButton jbtnexit;
    private javax.swing.JButton jbtnforgetpassword;
    private javax.swing.JButton jbtnlogin;
    private javax.swing.JButton jbtnsave;
    private javax.swing.JTextField jtxtanswer;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxtname;
    private javax.swing.JPasswordField jtxtpassword;
    private javax.swing.JTextField jtxtphone;
    private javax.swing.JTextField jtxtsq;
    // End of variables declaration//GEN-END:variables
}
